export default [
    {
      id: 1,
      postedOn: new Date(),
      title: "Frontend Developer",
      type: "Full time",
      location: "Remote",
      companyName: "Xoriant",
      companyUrl: "https://www.xoriant.com/",
      skills: ["React.js", "Node.js", "NoSQL", "Django"],
      link: "https://www.xoriant.com/about-xoriant/careers",
    },
    {
      id: 2,
      postedOn: new Date(),
      title: "Backend Developer",
      type: "Contract",
      location: "Bangalore",
      companyName: "Amadeus",
      companyUrl: "http://www.amadeus.in/",
      skills: ["Python", "DjangoORM"],
      link: "https://indeedhi.re/2P0OU0P",
    },
    {
      id: 3,
      postedOn: new Date(),
      title: "Sr. Python Developer",
      type: "Full time",
      location: "Remote",
      companyName: "Caledon Technologies",
      companyUrl: "http://caledontechnologies.com/",
      skills: ["React", "Node", "Django", "Python"],
      link: "https://indeedhi.re/3qY4Krd",
    },
    {
      id: 4,
      postedOn: new Date(),
      title: "Gradute Software Engineer",
      type: "Part time",
      location: "Bangalore",
      companyName: "Bottomline Technologies",
      companyUrl: "https://www.bottomline.com/us",
      skills: ["Python", "Problem solving", "Creative"],
      link: "https://www.bottomline.com/us/about/careers",
    },
    {
      id: 5,
      postedOn: new Date(),
      title: "Junior Backend Developer",
      type: "Part time",
      location: "Bangalore",
      companyName: "Finpoint",
      companyUrl: "https://gofinpoint.com/",
      skills: ["Django", "Linux", "RESTful API"],
      link: "https://gofinpoint.com/careers.html",
    },
    {
      id: 6,
      postedOn: new Date(),
      title: "Frontend Developer",
      type: "Contract",
      location: "Chennai",
      companyName: "PG Analytics",
      companyUrl: "http://www.pganalytics.in/about.html",
      skills: ["Django", "RabbitMQ", "AWS"],
      link: "http://www.pganalytics.in/contact.html",
    },  ];